### PR TITLE
fix(auth): stabilize login

### PR DESCRIPTION
**Pull request by tfenster**

### CODE REVIEW

**Comment by tfenster** [comment]
@DavidFeldhoff PTAL

**Comment by DavidFeldhoff** [comment]
What happens if there's another error (not a auth one) in the get Method? Then we would still return undefined and would still run into  the `Cannot read properties of undefined (reading 'value')` error in the `responseAccounts.value.forEach`-statement. 
That's why I would think it's better to check if the values we need are filled like this one.
Do you agree?

```typescript
export async function getOrganizations(): Promise<Organization[]> {
    try {
        let connection = getAzureDevOpsConnection();
        let memberId = await connection.getMemberId();
        // https://learn.microsoft.com/en-us/rest/api/azure/devops/account/accounts/list?view=azure-devops-rest-7.1&tabs=HTTP
        // This procedure will return only the data again as it was before the PR
        let responseAccounts = await connection.get(`https://app.vssps.visualstudio.com/_apis/accounts?memberId=${memberId}&api-version=6.0-preview.1`);
        if (!responseAccounts || !responseAccounts.value) {
            return [];
        }
        let orgs = new Array<Organization>();
        await responseAccounts.value.forEach((account: any) => {
            orgs.push(new Organization(account.accountName, `https://dev.azure.com/${account.accountName}`,
                account.accountId, vscode.TreeItemCollapsibleState.Collapsed));
        });
        orgs.sort((a, b) => a.label.localeCompare(b.label));
        return orgs;
    } catch (error) {
        vscode.window.showErrorMessage(`An unexpected error occurred while retrieving organizations: ${error}`);
        console.error(error);
        return [];
   }
}
```

The get method would look like this
```typescript
    public async get(url: string): Promise< any | undefined> {
        try {
            let token = await this.getToken();
            if (token === undefined) {
                return undefined;
            }
            const response = axios.get(url, {
                headers: {
                    // eslint-disable-next-line @typescript-eslint/naming-convention
                    "Authorization": `Bearer ${token.token}`
                }
            });
            return (await response).data;
        } catch (error) {
            vscode.window.showErrorMessage(`An unexpected error occurred during a get request to the backend: ${error}`);
            console.error(error);
            console.error(`url: ${url}`);
            return undefined;
        }
    }
```

**Comment by tfenster** [comment]
My idea was to differentiate between auth problems (already handled with a good error message in getToken) and other errors. I didn't handle the other errors yet, but we could do that in the calling methods. But if it is an auth problem, then the calling method just does nothing.

**Comment by DavidFeldhoff** [comment]
Ah. Did not see that, sorry. 

> Edit : To explain a bit better, if it is an Auth error, the calling method should do nothing, especially not show an error. 

Makes sense as the error is already thrown by `getToken`. I like that.

> If it isn't an Auth error, then the calling method should show an error. Probably a better one than we have, but if we just return undefined, then we can't differentiate.

Question to that: But in this current PR the calling method is not showing a better error, right? Or am I overlooking something (again)? Currently it's like this as far as I can see:
1. Auth error? `getToken` throws an error and neither `connection.get` nor `getOrganizations` *show* another error.
2. No auth error? `connection.get` *shows* an error (`An unexpected error occurred during a get request to the backend`). Furthermore `responseAccounts` in `getOrganizations` is undefined and would run into another error as we access `responseAccounts.responseData.value` (while responseAccounts` is already undefined). That's something we should definitely fix in my eyes.

Idea: We could simply forward the catched error in `connection.get` to the caller (e.g. `getOrganizations`, so that the error is not `An unexpected error occurred during a get request to the backend: ${error}`, but instead it is `An unexpected error occurred while retrieving organizations: ${error}`. With that we would skip as well the undefined access to `responseAccounts.responseData.value` as we're directly landing in the catched block..

**Comment by tfenster** [comment]
Good point. Now I implemented it differently:

1. I moved the backend calls in connection.ts into a generic method (should have done that in the very beginning, to be honest, actually not really connected to this issue)
2. If the backend call runs into an error, it logs that, but also throws the error again, to be handled by the caller. So basically exactly as you proposed, if I understood you correctly
3. A special case is when we run into an auth error (getToken is undefined). In that case, the function just returns undefined, but doesn't throw an error, so the caller can just quietly accept it.

Can you PTAL again?

**Comment by DavidFeldhoff** [comment]
Hi Tobias, I just added minor changes. 
`Try catch` around loading of work items as well and
Furthermore if there's an error in `getMemberId`, then undefined was returned, but that wasn't caught. 

I think it's fine now and I'd look forward to give it a try to see if these changes help the others with their sign in experience.

**Review by DavidFeldhoff — APPROVED** [review]

**Pull request merged**
