### PR TITLE
Ask for branch to base on when creating a new branch #28

### PR DESCRIPTION
**Pull request by DavidFeldhoff**
First version. @tfenster do you think we need a setting for it?
Like: baseOfNewBranch with the following options
- current branch
- ask me
- default branch of remote repo

### CODE REVIEW

**Comment by tfenster** [comment]
hm, I think it will annoy me if I always have to select it... VS Code has two actions, I think, "create branch" and "create branch from...", but that wouldn't work well with the icon action that we have

**Comment by DavidFeldhoff** [comment]
Get your point. And a setting might be too strict. I'll leave it as draft for now, maybe we find a better solution the next days

**Comment by tfenster** [comment]
Maybe we could have a "ask me: yes/no" toggle. That would also enable all scenarios, but might be easier to understand

**Comment by DavidFeldhoff** [comment]
So you mean a toggle that set's a setting? That enables indeed everything and we can add that. But I won't be able to make it today or the next week as it's pretty full for me and then I'm on vacation. If you can make it earlier, feel free to change it otherwise I'll pick it up later.

Just leaving this screenshot here as I noticed I didn't explained how it's working up until now:
image
You get asked, but the current branch is at the top, so that you can diretly enter it away. 2nd entry is the default branch of the remote and 3rd is the default branch as well, but in your local repo (don't know when I would use that option honestly). Then it's simply followed by all local, then all remote branches, but I think then I would use the search functionality anyway.

**Comment by DavidFeldhoff** [comment]
Just found some time adding it. The settings are now added, but the UI-Toggle to switch the "askForBaseBranch" one is still missing

**Comment by tfenster** [comment]
@DavidFeldhoff fine for me. I meant a boolean setting when I said "toogle", so I would accept this as is

**Comment by DavidFeldhoff** [comment]
Okay, I don't see it as necessary as well, so if you accept it, I'll close it

**Review by tfenster — APPROVED** [review]

**Pull request merged**
