### PR TITLE
Add setting `azdevops-vscode-simplify.organizationAndProjectFilter` ..

### PR DESCRIPTION
**Pull request by DavidFeldhoff**
to filter organizations and projects.

I added a setting where you can specify organization and project filters like
```json
"azdevops-vscode-simplify.organizationAndProjectFilter": [
  "My Organization/*",
  "My Organization2/* customizations"
]
```
I think that should solve the needs requested in #10 

Cheers,
David

### CODE REVIEW

**Comment by tfenster** [comment]
@DavidFeldhoff I hope I am not misunderstanding the code, but here are two concerns:

_Org filtering_
If I have something like `["*/* customizations"]` because I want to only see customization projects, then an org that doesn't contain any projects with "customizations" in the name would still show up, right? Just with no projects below. To be honest, I don't know how we can solve that, unless we load all projects in all orgs with the initial call, which imho doesn't make sense from a performance perspective. But I wanted to point it out, maybe you have an idea? But if not, also not a big issue, I would say a corner case that we can live with.

_Project filtering_
If I have a structure like this
```
- org 1
  - proj 1
  - proj 2
- org 2
  - proj 1
  - proj 2
```
  and I add a project filter like `["org 1/proj 1", "org 2/proj 2"`], then all projects would show with the current implementation, right? The orgs pass correctly, but because you only look at the projects part in the project filter, `org 1/proj 2` and `org 2/proj 1` would also pass. Again, probably a rare corner case, but this one we can probably fix easily by creating the regex for `<org>/<proj>` instead of only looking at the project.

**Comment by DavidFeldhoff** [comment]
Ehm yes you're totally right.

**Comment by DavidFeldhoff** [comment]
As you said the project filtering can easily be fixed, but the org part I'd skip, I think. I mean there its a tradeoff between performance and the functionality to define `*/* customizations`, but you could still define in your setting `org1/customizations`, `org2/customizations` etc.
And I think you'll not really have let's say >10 organizations which are having the save naming convention (with `customizations` at the end), right? And even if you'd have multiple organizations with that, the performance would be a poor one. That means I'd suggest the users to specify the organization names anyway.

**Comment by DavidFeldhoff** [comment]
Well, I just fixed the organization filtering as well, so that only organizations are shown that really have projects after the filtering is applied to see what the performance impact actually is and in my case it only took 1245 ms to load *all* organizations including the preload of their organizations. With that knowledge I'd leave it as it is as I think that's still acceptable. 
I tested it with `*/*(some part of existing project)*` and I waited with opening the DevOps view until all other extensions were loaded, because otherwise, if I opened it directly after opening VS Code, it took > 4 seconds, but I think that's not a valid use case. Furthermore: Only the projects are loaded of the organizations that already matched the org-filtering. So the ~1 seconds for me are already the worst case as I've filtered the organizations with `*`.
Maybe you can test it once more as you've quite some more organizations? But if that remains as well in an acceptable time frame, then I'd leave it as it is as it's now more intuitive for the user.
image

**Comment by DavidFeldhoff** [comment]
I'll respond to your comment (https://github.com/tfenster/azdevops-vscode-simplify/issues/10#issuecomment-1361017728) here: Yes, it seems I missed to push the package.json, even if I thought I published that as well. Sorry for the inconveniences.

What I did not push is the package-lock.json. Honestly because in other projects (ATDD) we decided to not track them in git and I don't get the point of the package-lock.json until now. Do you want me to push that as well or should we remove that from the git index as well?

**Comment by tfenster** [comment]
Timing is also fine for me, somewhere around 5 seconds (on mobile internet connection) with not a lot of organizations, but a ton of projects.

For package-lock.json: I investigated a bit at the time when I created my first extension and this https://docs.npmjs.com/cli/v6/configuring-npm/package-locks made sense to me, so i followed the suggestion to also add the lock.json

**Review by tfenster — DISMISSED** [review]

**Comment by DavidFeldhoff** [comment]
okay, then I updated the package-lock.json as well which requires a new approval :)

**Pull request merged**
